name: update

on:
  schedule:
    - cron: '00 00 * * 1'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Update
        run: git submodule foreach git pull origin master
        shell: bash
      - name: Commit and tag
        uses: EndBug/add-and-commit@v7
        with:
          add: '.'
          default_author: 'github_actions'
          message: 'Update to latest nextpnr'
          pull: 'NO-PULL'
          push: true
